### ISSUE TITLE
Set Up Windows CI On AppVeyor

### ISSUE THREAD

**Issue by joefitzgerald** [cloudfoundry-incubator/garden#17]
... because why not? It establishes proof of Windows compatibility. http://appveyor.com

For a rough example (which also does node stuff): https://github.com/joefitzgerald/go-plus/blob/54dffaf6720e236d7073561781332631b8cc5e4b/appveyor.yml

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#109274432](https://www.pivotaltracker.com/story/show/109274432) Set Up Windows CI On AppVeyor


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by goonzoid** [comment]
@joefitzgerald @stefanschneider Sorry we never acted on this. It's been a while now though, and I don't think we have any plans to do this.

Happy to re-open if this proves useful for someone, but I'll close for now.
