### ISSUE TITLE
Run a docker image

### ISSUE THREAD

**Issue by roldancer** [cloudfoundry-incubator/garden#27]
Hi, could someone tell me how to run a Docker image using Garden, I would like to understand how will be supported docker in CF.

Many thanks, an sorry if my questions was not posted in the right channel. :)

**Comment by tsaleh** [comment]
We recently updated the [`ContainerSpec` documentation](http://godoc.org/github.com/cloudfoundry-incubator/garden#ContainerSpec) to include the `docker://` url scheme for `RootFSPath`.
