### ISSUE TITLE
Executor should use keepalive with Garden

### ISSUE THREAD

**Issue by tsjsdbd** [cloudfoundry-incubator/garden#31]
Hi,

when using Diego, there are some many logs about the connection closed and open between Executor and Garden:
```
{"timestamp":"1427986534.529126406","source":"garden-linux","message":"garden-linux.connection.closed","log_level":0,"data":{"local_addr":{"IP":"127.0.0.1","Port":7777,"Zone":""},"remote_addr":{"IP":"127.0.0.1","Port":59895,"Zone":""},"session":"5"}}
{"timestamp":"1427986539.528430939","source":"garden-linux","message":"garden-linux.connection.open","log_level":0,"data":{"local_addr":{"IP":"127.0.0.1","Port":7777,"Zone":""},"remote_addr":{"IP":"127.0.0.1","Port":59896,"Zone":""},"session":"5"}}
{"timestamp":"1427986539.529073715","source":"garden-linux","message":"garden-linux.connection.closed","log_level":0,"data":{"local_addr":{"IP":"127.0.0.1","Port":7777,"Zone":""},"remote_addr":{"IP":"127.0.0.1","Port":59896,"Zone":""},"session":"5"}}
{"timestamp":"1427986543.679091215","source":"garden-linux","message":"garden-linux.connection.open","log_level":0,"data":{"local_addr":{"IP":"127.0.0.1","Port":7777,"Zone":""},"remote_addr":{"IP":"127.0.0.1","Port":59898,"Zone":""},"session":"5"}}
{"timestamp":"1427986543.679640770","source":"garden-linux","message":"garden-linux.connection.closed","log_level":0,"data":{"local_addr":{"IP":"127.0.0.1","Port":7777,"Zone":""},"remote_addr":{"IP":"127.0.0.1","Port":59898,"Zone":""},"session":"5"}}
{"timestamp":"1427986544.528329372","source":"garden-linux","message":"garden-linux.connection.open","log_level":0,"data":{"local_addr":{"IP":"127.0.0.1","Port":7777,"Zone":""},"remot
```
this is very annoying when debug something, and also the tcp connection always close and open is not necessory.

the [code here](https://github.com/cloudfoundry-incubator/garden/blob/master/client/connection/connection.go#L610) maybe can use a keepalive http client
@liuhewei @lyuyun

Thanks

**Comment by tsaleh** [comment]
Interesting.  It's not something that the garden team has had issues with, but I know @vito and @xoebus have cared about log verbosity in the past.

**Comment by tsjsdbd** [comment]
I was intend to open the issue in Executor's rep, but I found that Executor reference the Garden's client code, so open it here.

if keepalive is not always a good method, i think maybe a config flag can add to control the manner.
when Executor and Garden are in the same VM, we can choose keepalive between them.

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#109274426](https://www.pivotaltracker.com/story/show/109274426) Executor should use keepalive with Garden


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by goonzoid** [comment]
This was actually an issue in [Garden-Linux](https://github.com/cloudfoundry-incubator/garden-linux) rather than the garden client or server packages. I'll close this here.

I would open a new issue there, but we're in the process of sunsetting Garden-Linux in favour of [Guardian](https://github.com/cloudfoundry-incubator/guardian), which doesn't share this issue, so I don't think there's much point.
