### ISSUE TITLE
deny_networks on NetOut

### ISSUE THREAD

**Issue by benmoss** [cloudfoundry-incubator/garden#34]
Hi all,

https://github.com/cloudfoundry-incubator/garden/blob/771dc9b6304276a0a3efd2f1e60a7c7d0cd27b4c/container.go#L91-L92 mentions a `deny_networks` "configuration directive" but I can't find any other reference to it. Is this a real thing? We are looking to implement this API for garden-windows and want to make sure we understand it.

Best,
Ben

**Comment by julz** [comment]
It's a [flag accepted by garden-linux](https://github.com/cloudfoundry-incubator/garden-linux/blob/master/old/main.go#L134) which sets the networks which are denied by default (before NetOut rules add whitelist exceptions). Other backends would be expected to have a similar way to configure the base set of denied-by-default networks or to deny everything (or to allow everything by default but then NetOut is a no-op).

**Comment by benmoss** [comment]
Great, thank you!
