### ISSUE TITLE
grace_time should be specified in something other than nanoseconds

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry-incubator/garden#36]
Currently, when creating a container with a specific `grace_time`, the JSON unmarshaller puts the data directly into the `ContainerSpec.GraceTime` field, which is type `time.Duration` - an int64 representing nanoseconds. It would be very helpful if this instead accepted a string, that was parsed via `time.ParseDuration()`. This would also help in the case of people getting unmarshal errors when submitting `"grace_time":"1500"`, since the API requires an int in the payload.

At the very least, the docs regarding the grace_time field in the API should be updated to mention this, and use a real-example (current one uses a 1200 value for `grace_time`, which is only 12 microseconds).

**Comment by goonzoid** [comment]
Hi @geofffranks!

At present, the JSON/HTTP API is considered to be private, and isn't really supported for use without the garden go client (which uses a `time.Duration` for this). That may change in the future, but for now the go client is really the only supported way to interact with a Garden backend.

That said, I'd be curious to hear about your use case. What's led you down this path?

**Comment by geofffranks** [comment]
My use case is pretty out there. I'm using ConcourseCI to do some BOSH deployments, but have limited network access such that only the concourse workers have access to the various microboshes. In order to debug things with the bosh deployments, I'm hoping on the Concourse worker, spinning up a new garden/warden container (with custom grace time), and connecting to bosh through that, so that I don't need to install the bosh CLI on the worker VM itself. 

I wasn't aware that the API was considered private, so I'll check out the go client, and see if I can get that bundled in with the deployment, so I can use that from the worker VM, instead of manual curls.

**Comment by goonzoid** [comment]
If you just want a command line tool then gaol [1] works well and should be easy to bundle into your deployment so that it's installed on the workers. I'm not sure that it supports a grace time param for container creation, but I expect @xoebus would be open to a PR to add that, and it's probably trivial to do.

[1] https://github.com/xoebus/gaol

**Comment by goonzoid** [comment]
Well, I just checked, and gaol _does_ support custom grace times already. Good stuff!

**Comment by goonzoid** [comment]
I'm going to close this issue as I don't think there's anything needed from the Garden team here.
