### ISSUE TITLE
Garden API is not HTTP compliant

### ISSUE THREAD

**Issue by redbaron** [cloudfoundry-incubator/garden#44]
Right now Garden REST API isn't HTTP compliant which essentially changes it from REST to some proprietary protocol which only specially crafted libraries can talk.

2 cases found so far.

### POST /containers/:handle/processes reads input after response was given
When `POST`ing  to `/containers/:handle/processes` it produces 201 Response with process_id and stream_id and then continues to read data from client's socket for more input, such as input to the process's stdin. That is not how HTTP works, once response is given no more data related to original request can be read.

Correct behaviour would be to expect client to make another HTTP request, or at very least upgrade HTTP connection to a custom protocol as per HTTP/1.1 spec.

### /containers/:handle/processes/:pid doesn't produce chunked encoding, but advertises it in the response

Chunked encoding must be prefixed with a length of each chunk, garden doesn't do it, instead it just sends individual jsons in a comet-like fashion.

Example of a failing curl when attempting to query it:
```
$ curl -v 192.168.100.4:7777/containers/6l0a045dq2i/processes/4226
*   Trying 192.168.100.4...
* Connected to 192.168.100.4 (192.168.100.4) port 7777 (#0)
> GET /containers/6l0a045dq2i/processes/4226 HTTP/1.1
> Host: 192.168.100.4:7777
> User-Agent: curl/7.42.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Mon, 30 Nov 2015 15:53:19 GMT
< Content-Type: text/plain; charset=utf-8
< Transfer-Encoding: chunked
< 
* Illegal or missing hexadecimal sequence in chunked-encoding
* Closing connection 0
curl: (56) Illegal or missing hexadecimal sequence in chunked-encoding
```

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#109274416](https://www.pivotaltracker.com/story/show/109274416) Garden API is not HTTP compliant


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by goonzoid** [comment]
Hi @redbaron, thanks for raising this.

So sorry for the slow response. Somehow this slipped through the cracks!

Currently the Garden HTTP API is considered private, and the only supported way to use it it by using the Go client in this package. We may begin to officially support it in the future, but for now we're not dong any work on it that we don't need within the project I'm afraid. That said, we'd be more than happy to accept a PR that improves this!

Closing this issue though since there's nothing to be done on our part at the moment.
